using Dataverse.Plugins.Tooling.Codegen;
using Dataverse.Plugins.Tooling.Model;
using Xunit;

namespace Dataverse.Plugins.Tooling.Tests;

public class SchemaCodeGeneratorTests
{
    [Fact]
    public void IdentifiersComeFromSchemaNameAndValuesFromLogicalName()
    {
        // The whole point: "firstname" has no word boundaries, so only SchemaName can produce
        // a readable identifier.
        var code = Generate(Table("contact", "Contact", ("firstname", "FirstName")));

        Assert.Contains("public static class Contact", code);
        Assert.Contains("public const string EntityLogicalName = \"contact\";", code);
        Assert.Contains("public const string FirstName = \"firstname\";", code);
    }

    [Fact]
    public void MessagesBecomeConstants()
    {
        var snapshot = new SchemaSnapshot { Messages = ["Create", "Update"] };

        var code = SchemaCodeGenerator.Generate(snapshot);

        Assert.Contains("public const string Create = \"Create\";", code);
        Assert.Contains("public const string Update = \"Update\";", code);
    }

    [Fact]
    public void KeywordNamesAreEscapedRatherThanMangled()
    {
        var code = Generate(Table("thing", "Thing", ("event", "event")));

        Assert.Contains("public const string @event = \"event\";", code);
    }

    [Fact]
    public void NamesStartingWithADigitBecomeLegal()
    {
        var code = Generate(Table("thing", "Thing", ("1st", "1st")));

        Assert.Contains("public const string _1st = \"1st\";", code);
    }

    [Fact]
    public void CharactersThatAreNotLegalInAnIdentifierAreReplaced()
    {
        var code = Generate(Table("thing", "Thing", ("odd-name", "odd-name")));

        Assert.Contains("public const string odd_name = \"odd-name\";", code);
    }

    [Fact]
    public void ColumnsThatSanitiseToTheSameIdentifierAreDisambiguated()
    {
        var code = Generate(Table("thing", "Thing", ("a-b", "a-b"), ("a_b", "a_b")));

        Assert.Contains("= \"a-b\";", code);
        Assert.Contains("= \"a_b\";", code);
        Assert.Contains("a_b_2", code);
    }

    [Fact]
    public void ATableCalledMessagesDoesNotCollideWithTheMessagesClass()
    {
        var snapshot = new SchemaSnapshot
        {
            Messages = ["Create"],
            Tables = [Table("messages", "Messages", ("name", "Name"))],
        };

        var code = SchemaCodeGenerator.Generate(snapshot);

        Assert.Contains("public static class Messages_2", code);
        // The real Messages class must survive intact.
        Assert.Contains("public const string Create = \"Create\";", code);
    }

    [Fact]
    public void GeneratedFileIsMarkedAutoGenerated()
    {
        var code = SchemaCodeGenerator.Generate(new SchemaSnapshot());

        Assert.StartsWith("// <auto-generated/>", code);
        Assert.Contains($"namespace {SchemaCodeGenerator.Namespace}", code);
    }

    private static string Generate(SchemaTable table) =>
        SchemaCodeGenerator.Generate(new SchemaSnapshot { Tables = [table] });

    private static SchemaTable Table(
        string logicalName,
        string schemaName,
        params (string Logical, string Schema)[] columns) =>
        new()
        {
            LogicalName = logicalName,
            SchemaName = schemaName,
            Columns = columns
                .Select(column => new SchemaColumn { LogicalName = column.Logical, SchemaName = column.Schema })
                .ToList(),
        };
}
