// <auto-generated/>
//
// Generated from config/schema.json by 'dv schema codegen'. Do not edit by hand.
// Refresh a table with: dv schema pull --env <name> --tables <logical names>
//
// Linked into every plugin assembly by Abstractions.Sources.props. The values are
// const, so they inline at compile time and cost the assemblies nothing.

namespace Dataverse.Plugins.Abstractions.Schema
{
    /// <summary>SDK message names, for the message argument of [PluginStep].</summary>
    public static class Messages
    {
        public const string Assign = "Assign";
        public const string Associate = "Associate";
        public const string Create = "Create";
        public const string Delete = "Delete";
        public const string Disassociate = "Disassociate";
        public const string GrantAccess = "GrantAccess";
        public const string Merge = "Merge";
        public const string ModifyAccess = "ModifyAccess";
        public const string Retrieve = "Retrieve";
        public const string RetrieveMultiple = "RetrieveMultiple";
        public const string RevokeAccess = "RevokeAccess";
        public const string SetState = "SetState";
        public const string Update = "Update";
    }

    /// <summary>Table <c>account</c>.</summary>
    public static class Account
    {
        public const string EntityLogicalName = "account";

        /// <summary>Column logical names.</summary>
        public static class Fields
        {
            public const string AccountCategoryCode = "accountcategorycode";
            public const string AccountId = "accountid";
            public const string AccountNumber = "accountnumber";
            public const string CreatedOn = "createdon";
            public const string Description = "description";
            public const string EMailAddress1 = "emailaddress1";
            public const string ModifiedOn = "modifiedon";
            public const string Name = "name";
            public const string OwnerId = "ownerid";
            public const string PrimaryContactId = "primarycontactid";
            public const string StateCode = "statecode";
            public const string StatusCode = "statuscode";
            public const string Telephone1 = "telephone1";
        }
    }

    /// <summary>Table <c>contact</c>.</summary>
    public static class Contact
    {
        public const string EntityLogicalName = "contact";

        /// <summary>Column logical names.</summary>
        public static class Fields
        {
            public const string ContactId = "contactid";
            public const string CreatedOn = "createdon";
            public const string Description = "description";
            public const string EMailAddress1 = "emailaddress1";
            public const string FirstName = "firstname";
            public const string FullName = "fullname";
            public const string LastName = "lastname";
            public const string MiddleName = "middlename";
            public const string ModifiedOn = "modifiedon";
            public const string OwnerId = "ownerid";
            public const string ParentCustomerId = "parentcustomerid";
            public const string StateCode = "statecode";
            public const string StatusCode = "statuscode";
            public const string Telephone1 = "telephone1";
        }
    }
}
