using System.Text;
using Dataverse.Plugins.Tooling.Model;

namespace Dataverse.Plugins.Tooling.Codegen;

/// <summary>
/// Turns the committed schema snapshot into compile-time constants, so a mistyped table, column or
/// message is a build error instead of a step that deploys cleanly and never fires.
/// <para>
/// Identifiers come from metadata <c>SchemaName</c>, never <c>LogicalName</c>. Logical names are
/// lower-case with no word boundaries ("firstname"), so deriving an identifier from one gives
/// "Firstname"; the schema name already carries the casing ("FirstName").
/// </para>
/// </summary>
public static class SchemaCodeGenerator
{
    public const string Namespace = "Dataverse.Plugins.Abstractions.Schema";

    /// <summary>
    /// Reserved at namespace scope so a table called "Messages" cannot collide with the message
    /// constants class.
    /// </summary>
    private static readonly string[] ReservedTypeNames = ["Messages"];

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while",
    };

    public static string Generate(SchemaSnapshot snapshot)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("//");
        builder.AppendLine("// Generated from config/schema.json by 'dv schema codegen'. Do not edit by hand.");
        builder.AppendLine("// Refresh a table with: dv schema pull -e <name> -t <logical names>");
        builder.AppendLine("//");
        builder.AppendLine("// Linked into every plugin assembly by Abstractions.Sources.props. The values are");
        builder.AppendLine("// const, so they inline at compile time and cost the assemblies nothing.");
        builder.AppendLine();
        builder.AppendLine($"namespace {Namespace}");
        builder.AppendLine("{");

        AppendMessages(builder, snapshot.Messages);

        var usedTypeNames = new HashSet<string>(ReservedTypeNames, StringComparer.Ordinal);

        foreach (var table in snapshot.Tables.OrderBy(t => t.LogicalName, StringComparer.OrdinalIgnoreCase))
        {
            builder.AppendLine();
            AppendTable(builder, table, usedTypeNames);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendMessages(StringBuilder builder, IReadOnlyCollection<string> messages)
    {
        builder.AppendLine("    /// <summary>SDK message names, for the message argument of [PluginStep].</summary>");
        builder.AppendLine("    public static class Messages");
        builder.AppendLine("    {");

        if (messages.Count == 0)
        {
            builder.AppendLine("        // No messages in the snapshot yet. Run: dv schema pull --env <name> --tables <names>");
        }
        else
        {
            var used = new HashSet<string>(StringComparer.Ordinal);

            foreach (var message in messages.OrderBy(m => m, StringComparer.OrdinalIgnoreCase))
            {
                var identifier = UniqueIdentifier(message, used);
                builder.AppendLine($"        public const string {identifier} = \"{Escape(message)}\";");
            }
        }

        builder.AppendLine("    }");
    }

    private static void AppendTable(StringBuilder builder, SchemaTable table, HashSet<string> usedTypeNames)
    {
        var typeName = UniqueIdentifier(
            string.IsNullOrWhiteSpace(table.SchemaName) ? table.LogicalName : table.SchemaName,
            usedTypeNames);

        builder.AppendLine($"    /// <summary>Table <c>{table.LogicalName}</c>.</summary>");
        builder.AppendLine($"    public static class {typeName}");
        builder.AppendLine("    {");
        builder.AppendLine($"        public const string EntityLogicalName = \"{Escape(table.LogicalName)}\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Column logical names.</summary>");
        builder.AppendLine("        public static class Fields");
        builder.AppendLine("        {");

        var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var column in table.Columns.OrderBy(c => c.LogicalName, StringComparer.OrdinalIgnoreCase))
        {
            var identifier = UniqueIdentifier(
                string.IsNullOrWhiteSpace(column.SchemaName) ? column.LogicalName : column.SchemaName,
                usedFieldNames);

            builder.AppendLine($"            public const string {identifier} = \"{Escape(column.LogicalName)}\";");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
    }

    /// <summary>
    /// Makes a legal, unique C# identifier. Schema names are usually already legal; the awkward
    /// cases are custom columns with odd characters, and the rare name that collides after
    /// sanitising.
    /// </summary>
    private static string UniqueIdentifier(string candidate, HashSet<string> used)
    {
        var identifier = Sanitise(candidate);

        if (used.Add(identifier))
        {
            return identifier;
        }

        for (var suffix = 2; ; suffix++)
        {
            var attempt = $"{identifier}_{suffix}";

            if (used.Add(attempt))
            {
                return attempt;
            }
        }
    }

    private static string Sanitise(string candidate)
    {
        var builder = new StringBuilder(candidate.Length);

        foreach (var character in candidate)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        var identifier = builder.ToString();

        if (identifier.Length == 0)
        {
            return "_";
        }

        // An identifier may not start with a digit.
        if (char.IsDigit(identifier[0]))
        {
            identifier = "_" + identifier;
        }

        // A keyword is legal when escaped, which keeps the name recognisable.
        return CSharpKeywords.Contains(identifier) ? "@" + identifier : identifier;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
